#!/bin/bash
# set default monitor for gdm login screen
sudo cp ~/.config/monitors.xml ~gdm/.config/ && 
# set tap to click on gdm login screen
xhost SI:localuser:gdm
sudo -u gdm gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true &&
# install enable and start touchegg 
sudo dnf copr enable joseexposito/touchegg && 
sudo dnf install touchegg && 
sudo systemctl enable touchegg.service && 
sudo systemctl start touchegg 
